In [25]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [16]:
# Sample Sentences
sent=[ 'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [17]:
# Define Vocabulary Size
voc_size=10000


In [18]:
# One Hot Representation
one_hot_rep=[one_hot(words,voc_size)for words in sent]
print(one_hot_rep)

[[5939, 3866, 9543, 2527], [5939, 3866, 9543, 2975], [5939, 2761, 9543, 4183], [872, 1755, 7161, 2207, 5178], [872, 1755, 7161, 2207, 8934], [8167, 5939, 3911, 9543, 970], [775, 467, 7291, 2207]]


In [19]:
# word embedding representation
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5939 3866 9543 2527]
 [   0    0    0    0 5939 3866 9543 2975]
 [   0    0    0    0 5939 2761 9543 4183]
 [   0    0    0  872 1755 7161 2207 5178]
 [   0    0    0  872 1755 7161 2207 8934]
 [   0    0    0 8167 5939 3911 9543  970]
 [   0    0    0    0  775  467 7291 2207]]


In [20]:
# Feature Representation
dim=10

In [21]:
# Define Model
model=Sequential()
# add embedding layer
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile('adam','mse')

/home/saad-sohail/Desktop/IMDb-Movie-Review-Sentiment-Analysis/myenv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[[ 4.3823730e-02,  1.6578291e-02, -3.9734673e-02,  1.1300601e-02,
          4.8939217e-02, -3.9221533e-03, -1.9913800e-03, -2.1955943e-02,
          1.7837618e-02,  2.9664222e-02],
        [ 4.3823730e-02,  1.6578291e-02, -3.9734673e-02,  1.1300601e-02,
          4.8939217e-02, -3.9221533e-03, -1.9913800e-03, -2.1955943e-02,
          1.7837618e-02,  2.9664222e-02],
        [ 4.3823730e-02,  1.6578291e-02, -3.9734673e-02,  1.1300601e-02,
          4.8939217e-02, -3.9221533e-03, -1.9913800e-03, -2.1955943e-02,
          1.7837618e-02,  2.9664222e-02],
        [ 4.3823730e-02,  1.6578291e-02, -3.9734673e-02,  1.1300601e-02,
          4.8939217e-02, -3.9221533e-03, -1.9913800e-03, -2.1955943e-02,
          1.7837618e-02,  2.9664222e-02],
        [-4.3534961e-02, -3.6377452e-02,  2.7846862e-02,  3.0128248e-03,
          2.3098599e-02,  3.4373354e-02, -3.5083152e-02, -1.3940610e-02,
          2.5130082e-02,  3.7751887e-02],
        [ 1.8833641e-02,  4.8213352e-02, -3.7272431e-02,  5.

In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)